#!/bin/sh

uci -q set luci.main.lang='zh_cn'
uci -q set luci.main.mediaurlbase='/luci-static/argon'
uci -q commit luci

if [ -f /etc/config/dockerd ]; then
    uci -q set dockerd.globals.data_root='/opt/docker'
    uci -q commit dockerd
fi

exit 0
